### ISSUE TITLE
Inventree server trying to install plugin?

### ISSUE THREAD

**Issue by streeriver** [wolflu05/inventree-bulk-plugin#24]
I installed the plugin, activated it, etc. But now randomly my Inventree server crashes. Yesterday I just waited an hour and it came back. This time it isn't coming back. The logs for container inventree-server:

> Loading config file : /home/inventree/data/config.yaml
> InvenTree translation coverage: 22%
>   Running command git clone --filter=blob:none --quiet https://github.com/wolflu05/inventree-bulk-plugin /tmp/pip-install-60xmth91/inventree-bulk-plugin_a84603d5b73c45ee83e4ba3ec3c938f6
>   Running command git clone --filter=blob:none --quiet https://github.com/wolflu05/inventree-bulk-plugin /tmp/pip-install-pkh4wmxt/inventree-bulk-plugin_60fd3fce9f1f44a784999734cfc89c48
>   Running command git clone --filter=blob:none --quiet https://github.com/wolflu05/inventree-bulk-plugin /tmp/pip-install-rtxtkeoc/inventree-bulk-plugin_2bce36f50578499abc9124c73da0be75
>   Running command git clone --filter=blob:none --quiet https://github.com/wolflu05/inventree-bulk-plugin /tmp/pip-install-q_nt08c2/inventree-bulk-plugin_3b87ca1716d64b26ba131a145585e215
> [2023-02-16 18:19:04 +0000] [12] [CRITICAL] WORKER TIMEOUT (pid:13)
> [2023-02-16 18:19:04 +0000] [12] [CRITICAL] WORKER TIMEOUT (pid:14)
> [2023-02-16 18:19:04 +0000] [12] [CRITICAL] WORKER TIMEOUT (pid:15)
> [2023-02-16 18:19:04 +0000] [12] [CRITICAL] WORKER TIMEOUT (pid:16)
> [2023-02-16 18:19:05 +0000] [12] [WARNING] Worker with pid 14 was terminated due to signal 9
> [2023-02-16 18:19:05 +0000] [12] [WARNING] Worker with pid 16 was terminated due to signal 9
> [2023-02-16 18:19:05 +0000] [12] [WARNING] Worker with pid 13 was terminated due to signal 9
> [2023-02-16 18:19:05 +0000] [12] [WARNING] Worker with pid 15 was terminated due to signal 9
> ^C

I'm not sure if this is an Inventree error or a plugin error. Either way I can't disable or uninstall the plugin, as I can't access the server. I don't need it now, so if I can just disable it for now that's fine, till it gets fixed.

**Comment by wolflu05** [comment]
I think this is a general issue which already someone else had with plugins, but I don't render the exact solution. Maybe @matmair can help?

**Comment by matmair** [comment]
I'd suggest increasing the worker timeout - that is done via env or config.yaml
You can disable the plugin without the server running by either
- removing the plugin from your plugin.txt and uninstalling it from your env
- disabling plugins in your config.yaml and disabling the plugin in the settings (should start up then)

**Comment by streeriver** [comment]
Not sure how to access those without the container running?
I changed the worker timeout from 30 to 60, no affect.
I'm still learning docker. I ran the container and accessed it using 
`docker container exec -it inventree-server /bin/bash`
Then removed the plugin from
`/home/inventree/data/plugins.txt`
Then
`docker compose down && docker compose up -d`
Web interface came up right away and the logs aren't full of signal 9 errors.

Is there a fix for the plugin?

Thanks for the help!

**Comment by wolflu05** [comment]
Sorry, I don't think that is specific to this plugin, as it is working fine for me. What version of inventree are you actually using?

**Comment by streeriver** [comment]
I haven't worked on it at all. I uninstalled the plugin, but never fixed the issue. Sorry I missed your last question. I was using version 0.9.2.

**Comment by wolflu05** [comment]
Ok. So I'll close this. If you have any questions or issues feel free to open a new ticket.
