### ISSUE TITLE
Adding the location type as key

### ISSUE THREAD

**Issue by nikolai2111** [wolflu05/inventree-bulk-plugin#60]
I would very much appreciate it if the location type, which can be specified when creating a location, could also be set.

Just like the two parameters "Structural" and "External". There would only need to be a "Location Type" where you can select the type in the drop-down menu.

**Comment by wolflu05** [comment]
Hey @nikolai2111 ,

thanks for reporting. I already planned to add a few new fields (#59) in the next time but haven't prioritized it yet. I'll see if I can get to it in the next days. I'll notify you here if it is implemented.

May I ask you how you found out about this plugin, and what were your impressions about it? Was it easy to understand how it works?

Best
Lukas

**Comment by nikolai2111** [comment]
That sounds great! Thanks for the quick answer.

I found the plugin during my research on generating IPN via the categories.  I would like to create an IPN with a prefix that comes from the category. But that should not be possible at the moment. But I also saw that something similar is planned (#55).

**Comment by wolflu05** [comment]
So you want to automatically generate the IPN on creation of a new part (through the standard InvenTree interface, not this plugin) based on the categories? That's out of scope of this plugin. You are best off then, if you write your own plugin that uses the event Mixin and listens for part creation and then updates the IPN.

**Comment by nikolai2111** [comment]
Unfortunately, that is the answer I have already received.

I'm currently testing the whole thing and seeing if the system works for my area of application. In addition, no IPNs are necessary for me at the current stage, in any case I will create this plugin at a later date.

Ah and you asked me what my impressions of the plugin are, I'm currently very satisfied because it takes a lot of work off my hands. ;P

**Comment by nikolai2111** [comment]
Thank you!

**Comment by wolflu05** [comment]
No problem. Now also a release (v1.2.0) is created at [pypi](https://pypi.org/project/inventree-bulk-plugin/) so you just need to update inorder to have the new fields available.

> Ah and you asked me what my impressions of the plugin are, I'm currently very satisfied because it takes a lot of work off my hands. ;P

Thanks for that kind words. If there is anything unclear in the documentation feel free to ask.

**Comment by nikolai2111** [comment]
Thank you for the offer, I will keep it in mind. However, the plugin is very well documented.

Which is sometimes a bit more difficult for me with InvenTree itself, especially which fields are intended for what.

**Comment by nikolai2111** [comment]
> So you want to automatically generate the IPN on creation of a new part (through the standard InvenTree interface, not this plugin) based on the categories? That's out of scope of this plugin. You are best off then, if you write your own plugin that uses the event Mixin and listens for part creation and then updates the IPN.

Is there any way I can read the "current" index of the dim.1. so that I can calculate a pseudo IPN individual for each creation?

I mean, if I had these three values `{3,5,8}` as input, I could use the corresponding indices, like `1,2,3`.

**Comment by wolflu05** [comment]
Hello, no that is not possible yet, but seems like it's very easy to implement. I can add that in the next days.

**Comment by nikolai2111** [comment]
You are soooo fast man, I appreciate that!

You are soooo fast man, I appreciate it!

I solved it this way, but if it's directly embedded, that would be so grateful.

![grafik](https://github.com/wolflu05/inventree-bulk-plugin/assets/10119322/555c167a-5694-4056-a3f1-7b9112c9e8a4)

**Comment by wolflu05** [comment]
Interesting solution, thanks for sharing, I now created #68, please let me know if that would solve your problem.

**Comment by nikolai2111** [comment]
Thanks you!

A bit of tinkering but it worked great. It wasn't as parametric as I wanted, but that is to come. ;P

**Comment by wolflu05** [comment]
@nikolai2111 v1.2.2 is now released and available on pypi, so you just need to update the plugin. Then you have two new variables (`idx`, `dim.<x>.idx`) available like described [here](https://github.com/wolflu05/inventree-bulk-plugin?tab=readme-ov-file#generation-types). Please let me know if that solves your problem.
