### ISSUE TITLE
No UI showing

### ISSUE THREAD

**Issue by eiaro** [wolflu05/inventree-bulk-plugin#81]
I still have issue with the UI not showing up. Decided to open a new issue as my case wasn't closed by the solution in #80.

![image](https://github.com/user-attachments/assets/9a25bd2b-d71c-499e-adf6-c8922cc506ce)

### Version Information:
InvenTree-Version: 0.15.6
Django Version: 4.2.14
Commit Hash: 23a9485
Commit Date: 2024-07-23

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-6.1.0-10-amd64-x86_64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}, {'name': 'Brother Labels', 'slug': 'brother', 'version': '0.9.0'}, {'name': 'IPNGenerator', 'slug': 'ipngen', 'version': '0.1'}, {'name': 'InvenTreeBulkPlugin', 'slug': 'inventree-bulk-plugin', 'version': '1.3.0'}]

I have all Mixin enabled:
![image](https://github.com/user-attachments/assets/531b5fa2-6473-4819-854e-b1a4db9377dd)

`https://mydomain/static/inventree-bulk-plugin/dist/bulk-creation-panel.js` loads the .js file.

**Comment by wolflu05** [comment]
Not clear from your screenshot, but you need to manually create a root category/location. It will not show up when you're not viewing a details page for a category/location.

If that was not the issue, try restating your server, there could be some weird caching issues.

**Comment by eiaro** [comment]
Ah, so simple. Thanks for helping me get started.

**Comment by wolflu05** [comment]
Yes, adding the root category too, would have created a lot of unnecessary works, as I wasn't planing to use it on the root category anyway.

May I ask you how you found out about this plugin, and how you're liking it currently?

Best
Lukas

**Comment by eiaro** [comment]
Rather simple, I searched `inventree bulk` and this plugin was one of the first hits. 

I've had it running for less than one hour and it has saved me from manually entering 37 parts... And thats even before I start making locations that will be even more automated by this plugin as I can create a whole rack with boxes with boxes inside by just making one formula (I hope).

Most inventory softwares do have a very simplified function for getting started with matrix locations and such, but this plugin let you do everything you didn't imagine you needed.

So yeah... I like it a lot. Thanks for making it!

// eiaro

**Comment by wolflu05** [comment]
> I can create a whole rack with boxes with boxes inside by just making one formula

Exactly. You can even save the template for a rack or tower and reuse it a couple of times, also with different input parameters.

> Most inventory softwares do have a very simplified function for getting started with matrix locations and such, but this plugin let you do everything you didn't imagine you needed. So yeah... I like it a lot. Thanks for making it!

Actually, I'm sadly not aware of any other inventory solutions, and how they offer a matrix solution. I have just built this plugin based on my personal thinking and needs. So I'm happy it fits you well.


Feel free to also comment on the documentation. It is a hard process of writing a simple to understand documentation as a developer for a program that offers lots of complex functionality. May I also ask you: Was it easy to understand and get startet?

Best
Lukas
